package com.owner.test.entity;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.id
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.url
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.id
     *
     * @return the value of test..permission.id
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.id
     *
     * @param id the value for test..permission.id
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.url
     *
     * @return the value of test..permission.url
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.url
     *
     * @param url the value for test..permission.url
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", url=").append(url);
        sb.append("]");
        return sb.toString();
    }
}