package com.owner.test.mapper;

import com.owner.test.entity.Address;

public interface AddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test..address
	 * @mbggenerated  Wed Sep 11 11:25:53 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test..address
	 * @mbggenerated  Wed Sep 11 11:25:53 CST 2019
	 */
	int insert(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test..address
	 * @mbggenerated  Wed Sep 11 11:25:53 CST 2019
	 */
	int insertSelective(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test..address
	 * @mbggenerated  Wed Sep 11 11:25:53 CST 2019
	 */
	Address selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test..address
	 * @mbggenerated  Wed Sep 11 11:25:53 CST 2019
	 */
	int updateByPrimaryKeySelective(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test..address
	 * @mbggenerated  Wed Sep 11 11:25:53 CST 2019
	 */
	int updateByPrimaryKey(Address record);
}