package com.owner.test.mapper;

import com.owner.test.entity.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbggenerated Sat Sep 28 14:37:06 CST 2019
     */
    int updateByPrimaryKey(Permission record);
}